### ISSUE TITLE
Crash on load while attempting to edit drops for Natura Bloodwood Leaves

### ISSUE THREAD

**Issue by 666lumberjack** [codetaylor/dropt#26]
Crash Log: https://paste.ee/p/QrFjY
Relevant JSON: https://paste.ee/p/UHevy

Relevant Versions:
MC 1.12.2
Forge 2629
athenaeum 1.14.0
dropt 1.9.1
mantle 1.3.1.21
natura 4.3.2.42

**Comment by codetaylor** [comment]
Thanks for the report!

This is happening because there is a trailing comma in the `drops` array, just after the one object in the array. This causes Gson to interpret this as an array of `[RuleDrop, null]` and the subsequent NPE failure. I will add a null check to prevent this, in the meantime, removing the comma will solve your issue. :)

**Comment by codetaylor** [comment]
Fixed in 1.12.2-1.9.2

**Comment by 666lumberjack** [comment]
Figures I'd fuck up the syntax somewhere. Thanks for the quick fix!
