### ISSUE TITLE
Drops of falling entity

### ISSUE THREAD

**Issue by mobeonsa** [codetaylor/dropt#35]
Is there a way to config drop from falling entity? (Then sand fall on torch)

**Comment by codetaylor** [comment]
Unfortunately, that is something that Dropt doesn't handle.

Falling blocks use ...

```java
public EntityItem entityDropItem(ItemStack stack, float offsetY)
```

... to ultimately spawn the dropped item directly into the world. This bypasses the harvest event that Dropt uses to match and replace. Spawning the dropped item in the world does fire an `EntityJoinWorldEvent`, but it can't be used by Dropt because it doesn't deliver enough information. The join world event only notifies of the entity joining the world, not where it came from.
