### ISSUE TITLE
[Question] Can XP drops have a chance less than 100%

### ISSUE THREAD

**Issue by donqixot** [codetaylor/dropt#47]
I understand it is possible to specify XP drops with minimum of 1. But what if you want only 20% chance of XP drops? Can I use fractions?

**Comment by codetaylor** [comment]
To clarify, you want some number of XP to drop only 20% of the time?

Also, if you're interested, I now have a discord for my mods: discord.gg/HY69E8X

**Comment by donqixot** [comment]
Yes, exactly, thank you!

**Comment by codetaylor** [comment]
Yes, it is possible.

You want to have two items in your drop list. The first item will contain the XP you want to drop, and a selector with a weight. The second item will be empty, and have a selector with a different weight.

This describes the selector and XP object: https://dropt.readthedocs.io/en/latest/json/syntax/#iruledrop

It'll be similar to the first example [on this page](https://dropt.readthedocs.io/en/latest/json/examples/), but instead of a dye item you'd use the XP object.

Let me know if you would like further assistance.

**Comment by donqixot** [comment]
Thank you very much! I will close this for now, if I have further questions, I can always reopen.
