### ISSUE TITLE
Certain Blocks don't seem to drop 

### ISSUE THREAD

**Issue by IonFoXx** [codetaylor/dropt#63]
Hi,

I'm currently working on adding some drops to snow blocks when a player breaks the block with an empty hand. Apparently those don't seem to work for me for some reason.

This is the .json for my drops:
https://pastebin.com/BLVWJVgw

As soon as I remove the harvester match and break the block with a shovel everything seems to work correctly. I figured it could be something with the harvest level or tool used to break the block but I'm not to sure about that.

I also tried /dropt verbose and the block breaking doesn't get caught in the log files.

#### Affected Versions
Minecraft: 1.12.2
Dropt: 1.16.1 (dropt-1.12.2-1.16.1.jar)
Forge: 14.23.5.2846
CraftTweaker: 4.1.19
Athenaeum: 1.17.4

I hope I included all necessary information. Otherwise please just let me know if I missed something.

Best regards,
FoXx

**Comment by codetaylor** [comment]
Right. It's likely because Dropt doesn't work on blocks if they're harvested with a tool that doesn't match it's harvest tool type and harvest level. Snow blocks iirc can only be collected with a shovel. You'll have to use another mod to set the block's harvest tool / level to work with an empty hand.

`/dropt verbose` should work if you break the block with a shovel in survival mode. It won't work in creative or if the block is broken with a tool outside its valid harvest tool / level.

I also have a Discord set up for script help: discord.codetaylor.com

**Comment by IonFoXx** [comment]
Well I thought that might be the reason but I wasn't to sure about it. But thanks for clarifying and pointing me into the right direction.

**Comment by codetaylor** [comment]
You're welcome :)
